/* database.js */

// 1. ADIM: Bana attığın listeyi bu köşeli parantezlerin içine yapıştır:
const rawFootballData = [
  // --- MANCHESTER CITY ---
  { "id": 1, "name": "Gianluigi Donnarumma", "position": "GK", "rating": 89, "team": "Manchester City" },
  { "id": 2, "name": "Rico Lewis", "position": "DEF", "rating": 81, "team": "Manchester City" },
  { "id": 3, "name": "Rúben Dias", "position": "DEF", "rating": 89, "team": "Manchester City" },
  { "id": 4, "name": "Joško Gvardiol", "position": "DEF", "rating": 87, "team": "Manchester City" },
  { "id": 5, "name": "Rayan Aït-Nouri", "position": "DEF", "rating": 82, "team": "Manchester City" },
  { "id": 6, "name": "Rodri", "position": "MID", "rating": 92, "team": "Manchester City" },
  { "id": 7, "name": "Tijjani Reijnders", "position": "MID", "rating": 84, "team": "Manchester City" },
  { "id": 8, "name": "Kevin De Bruyne", "position": "MID", "rating": 88, "team": "Manchester City" },
  { "id": 9, "name": "Rayan Cherki", "position": "MID", "rating": 80, "team": "Manchester City" },
  { "id": 10, "name": "Antoine Semenyo", "position": "FWD", "rating": 81, "team": "Manchester City" },
  { "id": 11, "name": "Erling Haaland", "position": "FWD", "rating": 95, "team": "Manchester City" },
  { "id": 12, "name": "James Trafford", "position": "GK", "rating": 78, "team": "Manchester City" },
  { "id": 13, "name": "Stefan Ortega", "position": "GK", "rating": 79, "team": "Manchester City" },
  { "id": 14, "name": "John Stones", "position": "DEF", "rating": 86, "team": "Manchester City" },
  { "id": 15, "name": "Nathan Aké", "position": "DEF", "rating": 84, "team": "Manchester City" },
  { "id": 16, "name": "Marc Guehi", "position": "DEF", "rating": 83, "team": "Manchester City" },
  { "id": 17, "name": "Abdukodir Khusanov", "position": "DEF", "rating": 76, "team": "Manchester City" },
  { "id": 18, "name": "Mateo Kovačić", "position": "MID", "rating": 84, "team": "Manchester City" },
  { "id": 19, "name": "Matheus Nunes", "position": "MID", "rating": 81, "team": "Manchester City" },
  { "id": 20, "name": "Bernardo Silva", "position": "MID", "rating": 87, "team": "Manchester City" },
  { "id": 21, "name": "Phil Foden", "position": "MID", "rating": 90, "team": "Manchester City" },
  { "id": 22, "name": "Nico O'Reilly", "position": "MID", "rating": 70, "team": "Manchester City" },
  { "id": 23, "name": "Jérémy Doku", "position": "FWD", "rating": 84, "team": "Manchester City" },
  { "id": 24, "name": "Savinho", "position": "FWD", "rating": 82, "team": "Manchester City" },
  { "id": 25, "name": "Oscar Bobb", "position": "FWD", "rating": 78, "team": "Manchester City" },
  { "id": 26, "name": "Claudio Echeverri", "position": "FWD", "rating": 77, "team": "Manchester City" },

  // --- ARSENAL ---
  { "id": 27, "name": "David Raya", "position": "GK", "rating": 85, "team": "Arsenal" },
  { "id": 28, "name": "Ben White", "position": "DEF", "rating": 84, "team": "Arsenal" },
  { "id": 29, "name": "William Saliba", "position": "DEF", "rating": 89, "team": "Arsenal" },
  { "id": 30, "name": "Gabriel Magalhães", "position": "DEF", "rating": 87, "team": "Arsenal" },
  { "id": 31, "name": "Jurriën Timber", "position": "DEF", "rating": 83, "team": "Arsenal" },
  { "id": 32, "name": "Declan Rice", "position": "MID", "rating": 89, "team": "Arsenal" },
  { "id": 33, "name": "Mikel Merino", "position": "MID", "rating": 83, "team": "Arsenal" },
  { "id": 34, "name": "Martin Ødegaard", "position": "MID", "rating": 90, "team": "Arsenal" },
  { "id": 35, "name": "Bukayo Saka", "position": "FWD", "rating": 90, "team": "Arsenal" },
  { "id": 36, "name": "Gabriel Martinelli", "position": "FWD", "rating": 85, "team": "Arsenal" },
  { "id": 37, "name": "Viktor Gyökeres", "position": "FWD", "rating": 86, "team": "Arsenal" },
  { "id": 38, "name": "Kepa Arrizabalaga", "position": "GK", "rating": 79, "team": "Arsenal" },
  { "id": 39, "name": "Tommy Setford", "position": "GK", "rating": 68, "team": "Arsenal" },
  { "id": 40, "name": "Riccardo Calafiori", "position": "DEF", "rating": 81, "team": "Arsenal" },
  { "id": 41, "name": "Piero Hincapié", "position": "DEF", "rating": 82, "team": "Arsenal" },
  { "id": 42, "name": "Takehiro Tomiyasu", "position": "DEF", "rating": 80, "team": "Arsenal" },
  { "id": 43, "name": "Jakub Kiwior", "position": "DEF", "rating": 79, "team": "Arsenal" },
  { "id": 44, "name": "Oleksandr Zinchenko", "position": "DEF", "rating": 81, "team": "Arsenal" },
  { "id": 45, "name": "Cristhian Mosquera", "position": "DEF", "rating": 78, "team": "Arsenal" },
  { "id": 46, "name": "Thomas Partey", "position": "MID", "rating": 82, "team": "Arsenal" },
  { "id": 47, "name": "Jorginho", "position": "MID", "rating": 81, "team": "Arsenal" },
  { "id": 48, "name": "Ethan Nwaneri", "position": "MID", "rating": 72, "team": "Arsenal" },
  { "id": 49, "name": "Christian Nørgaard", "position": "MID", "rating": 79, "team": "Arsenal" },
  { "id": 50, "name": "Martín Zubimendi", "position": "MID", "rating": 84, "team": "Arsenal" },
  { "id": 51, "name": "Kai Havertz", "position": "FWD", "rating": 84, "team": "Arsenal" },
  { "id": 52, "name": "Leandro Trossard", "position": "FWD", "rating": 82, "team": "Arsenal" },
  { "id": 53, "name": "Gabriel Jesus", "position": "FWD", "rating": 83, "team": "Arsenal" },
  { "id": 54, "name": "Raheem Sterling", "position": "FWD", "rating": 80, "team": "Arsenal" },
  { "id": 55, "name": "Louie Copley", "position": "MID", "rating": 62, "team": "Crawley Town" }, // Kiralık gönderildi
  { "id": 56, "name": "Harrison Dudziak", "position": "MID", "rating": 63, "team": "Braintree" }, // Kiralık gönderildi

  // --- LIVERPOOL ---
  { "id": 57, "name": "Alisson Becker", "position": "GK", "rating": 89, "team": "Liverpool" },
  { "id": 58, "name": "Jeremie Frimpong", "position": "DEF", "rating": 86, "team": "Liverpool" },
  { "id": 59, "name": "Ibrahima Konaté", "position": "DEF", "rating": 85, "team": "Liverpool" },
  { "id": 60, "name": "Virgil van Dijk", "position": "DEF", "rating": 88, "team": "Liverpool" },
  { "id": 61, "name": "Milos Kerkez", "position": "DEF", "rating": 80, "team": "Liverpool" },
  { "id": 62, "name": "Alexis Mac Allister", "position": "MID", "rating": 86, "team": "Liverpool" },
  { "id": 63, "name": "Dominik Szoboszlai", "position": "MID", "rating": 86, "team": "Liverpool" },
  { "id": 64, "name": "Florian Wirtz", "position": "MID", "rating": 89, "team": "Liverpool" },
  { "id": 65, "name": "Mohamed Salah", "position": "FWD", "rating": 88, "team": "Liverpool" },
  { "id": 66, "name": "Cody Gakpo", "position": "FWD", "rating": 84, "team": "Liverpool" },
  { "id": 67, "name": "Alexander Isak", "position": "FWD", "rating": 87, "team": "Liverpool" },
  { "id": 68, "name": "Giorgi Mamardashvili", "position": "GK", "rating": 83, "team": "Liverpool" },
  { "id": 69, "name": "Freddie Woodman", "position": "GK", "rating": 76, "team": "Liverpool" },
  { "id": 70, "name": "Joe Gomez", "position": "DEF", "rating": 80, "team": "Liverpool" },
  { "id": 71, "name": "Giovanni Leoni", "position": "DEF", "rating": 72, "team": "Liverpool" },
  { "id": 72, "name": "Conor Bradley", "position": "DEF", "rating": 78, "team": "Liverpool" },
  { "id": 73, "name": "Andrew Robertson", "position": "DEF", "rating": 83, "team": "Liverpool" },
  { "id": 74, "name": "Owen Beck", "position": "DEF", "rating": 70, "team": "Liverpool" },
  { "id": 75, "name": "Curtis Jones", "position": "MID", "rating": 81, "team": "Liverpool" },
  { "id": 76, "name": "Ryan Gravenberch", "position": "MID", "rating": 82, "team": "Liverpool" },
  { "id": 77, "name": "Wataru Endo", "position": "MID", "rating": 79, "team": "Liverpool" },
  { "id": 78, "name": "Stefan Bajcetic", "position": "MID", "rating": 77, "team": "Liverpool" },
  { "id": 79, "name": "Federico Chiesa", "position": "FWD", "rating": 82, "team": "Liverpool" },
  { "id": 80, "name": "Hugo Ekitike", "position": "FWD", "rating": 79, "team": "Liverpool" },
  { "id": 81, "name": "Diogo Jota", "position": "FWD", "rating": 84, "team": "Liverpool" },
  { "id": 82, "name": "Mor Talla Ndiaye", "position": "MID", "rating": 65, "team": "Liverpool" },

  // --- MANCHESTER UNITED ---
  { "id": 83, "name": "Altay Bayindir", "position": "GK", "rating": 79, "team": "Manchester United" },
  { "id": 84, "name": "Diogo Dalot", "position": "DEF", "rating": 83, "team": "Manchester United" },
  { "id": 85, "name": "Matthijs de Ligt", "position": "DEF", "rating": 85, "team": "Manchester United" },
  { "id": 86, "name": "Lisandro Martínez", "position": "DEF", "rating": 85, "team": "Manchester United" },
  { "id": 87, "name": "Luke Shaw", "position": "DEF", "rating": 81, "team": "Manchester United" },
  { "id": 88, "name": "Manuel Ugarte", "position": "MID", "rating": 83, "team": "Manchester United" },
  { "id": 89, "name": "Kobbie Mainoo", "position": "MID", "rating": 82, "team": "Manchester United" },
  { "id": 90, "name": "Bruno Fernandes", "position": "MID", "rating": 86, "team": "Manchester United" },
  { "id": 91, "name": "Bryan Mbeumo", "position": "FWD", "rating": 82, "team": "Manchester United" },
  { "id": 92, "name": "Matheus Cunha", "position": "FWD", "rating": 82, "team": "Manchester United" },
  { "id": 93, "name": "Benjamin Šeško", "position": "FWD", "rating": 83, "team": "Manchester United" },
  { "id": 94, "name": "Tom Heaton", "position": "GK", "rating": 72, "team": "Manchester United" },
  { "id": 95, "name": "Harry Maguire", "position": "DEF", "rating": 79, "team": "Manchester United" },
  { "id": 96, "name": "Leny Yoro", "position": "DEF", "rating": 78, "team": "Manchester United" },
  { "id": 97, "name": "Noussair Mazraoui", "position": "DEF", "rating": 81, "team": "Manchester United" },
  { "id": 98, "name": "Tyrell Malacia", "position": "DEF", "rating": 77, "team": "Manchester United" },
  { "id": 99, "name": "Casemiro", "position": "MID", "rating": 81, "team": "Manchester United" },
  { "id": 100, "name": "Mason Mount", "position": "MID", "rating": 80, "team": "Manchester United" },
  { "id": 101, "name": "Toby Collyer", "position": "MID", "rating": 68, "team": "Manchester United" },
  { "id": 102, "name": "Joshua Zirkzee", "position": "FWD", "rating": 79, "team": "Manchester United" },
  { "id": 103, "name": "Amad Diallo", "position": "FWD", "rating": 79, "team": "Manchester United" },
  { "id": 104, "name": "Rasmus Højlund", "position": "FWD", "rating": 81, "team": "Napoli" }, // Kiralık

  // --- CHELSEA ---
  { "id": 105, "name": "Robert Sánchez", "position": "GK", "rating": 80, "team": "Chelsea" },
  { "id": 106, "name": "Reece James", "position": "DEF", "rating": 85, "team": "Chelsea" },
  { "id": 107, "name": "Wesley Fofana", "position": "DEF", "rating": 81, "team": "Chelsea" },
  { "id": 108, "name": "Levi Colwill", "position": "DEF", "rating": 81, "team": "Chelsea" },
  { "id": 109, "name": "Marc Cucurella", "position": "DEF", "rating": 80, "team": "Chelsea" },
  { "id": 110, "name": "Moisés Caicedo", "position": "MID", "rating": 85, "team": "Chelsea" },
  { "id": 111, "name": "Enzo Fernández", "position": "MID", "rating": 84, "team": "Chelsea" },
  { "id": 112, "name": "Cole Palmer", "position": "MID", "rating": 88, "team": "Chelsea" },
  { "id": 113, "name": "Pedro Neto", "position": "FWD", "rating": 82, "team": "Chelsea" },
  { "id": 114, "name": "Nicolas Jackson", "position": "FWD", "rating": 82, "team": "Bayern Münih" }, // Kiralık notu Bayern bölümünde
  { "id": 115, "name": "Filip Jörgensen", "position": "GK", "rating": 77, "team": "Chelsea" },
  { "id": 116, "name": "Malo Gusto", "position": "DEF", "rating": 80, "team": "Chelsea" },
  { "id": 117, "name": "Tosin Adarabioyo", "position": "DEF", "rating": 78, "team": "Chelsea" },
  { "id": 118, "name": "Benoît Badiashile", "position": "DEF", "rating": 78, "team": "Chelsea" },
  { "id": 119, "name": "Jorrel Hato", "position": "DEF", "rating": 79, "team": "Chelsea" },
  { "id": 120, "name": "Roméo Lavia", "position": "MID", "rating": 78, "team": "Chelsea" },
  { "id": 121, "name": "Andrey Santos", "position": "MID", "rating": 77, "team": "Chelsea" },
  { "id": 122, "name": "Kiernan Dewsbury-Hall", "position": "MID", "rating": 78, "team": "Chelsea" },
  { "id": 123, "name": "Alejandro Garnacho", "position": "FWD", "rating": 83, "team": "Chelsea" },
  { "id": 124, "name": "Estêvão Willian", "position": "FWD", "rating": 78, "team": "Chelsea" },
  { "id": 125, "name": "Mykhailo Mudryk", "position": "FWD", "rating": 79, "team": "Chelsea" },
  { "id": 126, "name": "Noni Madueke", "position": "FWD", "rating": 80, "team": "Chelsea" },
  { "id": 127, "name": "João Pedro", "position": "FWD", "rating": 81, "team": "Chelsea" },
  { "id": 128, "name": "Liam Delap", "position": "FWD", "rating": 75, "team": "Chelsea" },
  { "id": 129, "name": "Facundo Buonanotte", "position": "MID", "rating": 77, "team": "Chelsea" },

  // --- ASTON VILLA ---
  { "id": 130, "name": "Emiliano Martínez", "position": "GK", "rating": 89, "team": "Aston Villa" },
  { "id": 131, "name": "Matty Cash", "position": "DEF", "rating": 80, "team": "Aston Villa" },
  { "id": 132, "name": "Ezri Konsa", "position": "DEF", "rating": 82, "team": "Aston Villa" },
  { "id": 133, "name": "Pau Torres", "position": "DEF", "rating": 83, "team": "Aston Villa" },
  { "id": 134, "name": "Ian Maatsen", "position": "DEF", "rating": 80, "team": "Aston Villa" },
  { "id": 135, "name": "Leon Bailey", "position": "FWD", "rating": 82, "team": "Aston Villa" },
  { "id": 136, "name": "Amadou Onana", "position": "MID", "rating": 83, "team": "Aston Villa" },
  { "id": 137, "name": "Youri Tielemans", "position": "MID", "rating": 83, "team": "Aston Villa" },
  { "id": 138, "name": "Morgan Rogers", "position": "FWD", "rating": 78, "team": "Aston Villa" },
  { "id": 139, "name": "Harvey Elliott", "position": "MID", "rating": 80, "team": "Aston Villa" },
  { "id": 140, "name": "Ollie Watkins", "position": "FWD", "rating": 86, "team": "Aston Villa" },
  { "id": 141, "name": "Marco Bizot", "position": "GK", "rating": 78, "team": "Aston Villa" },
  { "id": 142, "name": "Tyrone Mings", "position": "DEF", "rating": 78, "team": "Aston Villa" },
  { "id": 143, "name": "Victor Lindelöf", "position": "DEF", "rating": 79, "team": "Aston Villa" },
  { "id": 144, "name": "Lucas Digne", "position": "DEF", "rating": 80, "team": "Aston Villa" },
  { "id": 145, "name": "Andrés García", "position": "DEF", "rating": 70, "team": "Aston Villa" },
  { "id": 146, "name": "Ross Barkley", "position": "MID", "rating": 77, "team": "Aston Villa" },
  { "id": 147, "name": "John McGinn", "position": "MID", "rating": 82, "team": "Aston Villa" },
  { "id": 148, "name": "Boubacar Kamara", "position": "MID", "rating": 82, "team": "Aston Villa" },
  { "id": 149, "name": "Emiliano Buendía", "position": "MID", "rating": 79, "team": "Aston Villa" },
  { "id": 150, "name": "Jadon Sancho", "position": "FWD", "rating": 81, "team": "Aston Villa" },
  { "id": 151, "name": "Evann Guessand", "position": "FWD", "rating": 77, "team": "Aston Villa" },
  { "id": 152, "name": "Alysson", "position": "FWD", "rating": 75, "team": "Aston Villa" },
  { "id": 153, "name": "Brian Madjo", "position": "FWD", "rating": 73, "team": "Aston Villa" },
  { "id": 154, "name": "Donyell Malen", "position": "FWD", "rating": 81, "team": "Roma" }, // Kiralık

  // --- REAL MADRID ---
  { "id": 155, "name": "Thibaut Courtois", "position": "GK", "rating": 90, "team": "Real Madrid" },
  { "id": 156, "name": "Trent Alexander-Arnold", "position": "DEF", "rating": 88, "team": "Real Madrid" },
  { "id": 157, "name": "Éder Militão", "position": "DEF", "rating": 86, "team": "Real Madrid" },
  { "id": 158, "name": "Antonio Rüdiger", "position": "DEF", "rating": 87, "team": "Real Madrid" },
  { "id": 159, "name": "Ferland Mendy", "position": "DEF", "rating": 83, "team": "Real Madrid" },
  { "id": 160, "name": "Federico Valverde", "position": "MID", "rating": 90, "team": "Real Madrid" },
  { "id": 161, "name": "Aurélien Tchouaméni", "position": "MID", "rating": 86, "team": "Real Madrid" },
  { "id": 162, "name": "Jude Bellingham", "position": "MID", "rating": 93, "team": "Real Madrid" },
  { "id": 163, "name": "Rodrygo", "position": "FWD", "rating": 87, "team": "Real Madrid" },
  { "id": 164, "name": "Vinícius Júnior", "position": "FWD", "rating": 92, "team": "Real Madrid" },
  { "id": 165, "name": "Kylian Mbappé", "position": "FWD", "rating": 94, "team": "Real Madrid" },
  { "id": 166, "name": "Andriy Lunin", "position": "GK", "rating": 82, "team": "Real Madrid" },
  { "id": 167, "name": "Dani Carvajal", "position": "DEF", "rating": 84, "team": "Real Madrid" },
  { "id": 168, "name": "David Alaba", "position": "DEF", "rating": 84, "team": "Real Madrid" },
  { "id": 169, "name": "Dean Huijsen", "position": "DEF", "rating": 77, "team": "Real Madrid" },
  { "id": 170, "name": "Fran García", "position": "DEF", "rating": 80, "team": "Real Madrid" },
  { "id": 171, "name": "Álvaro Carreras", "position": "DEF", "rating": 76, "team": "Real Madrid" },
  { "id": 172, "name": "Eduardo Camavinga", "position": "MID", "rating": 86, "team": "Real Madrid" },
  { "id": 173, "name": "Arda Güler", "position": "MID", "rating": 81, "team": "Real Madrid" },
  { "id": 174, "name": "Dani Ceballos", "position": "MID", "rating": 79, "team": "Real Madrid" },
  { "id": 175, "name": "Brahim Díaz", "position": "FWD", "rating": 82, "team": "Real Madrid" },
  { "id": 176, "name": "Gonzalo García", "position": "FWD", "rating": 70, "team": "Real Madrid" },
  { "id": 177, "name": "Franco Mastantuono", "position": "MID", "rating": 75, "team": "Real Madrid" },
  { "id": 178, "name": "Endrick", "position": "FWD", "rating": 78, "team": "Lyon" }, // Kiralık

  // --- BARCELONA ---
  { "id": 179, "name": "Marc-André ter Stegen", "position": "GK", "rating": 88, "team": "Barcelona" },
  { "id": 180, "name": "Jules Koundé", "position": "DEF", "rating": 85, "team": "Barcelona" },
  { "id": 181, "name": "Ronald Araújo", "position": "DEF", "rating": 86, "team": "Barcelona" },
  { "id": 182, "name": "Pau Cubarsí", "position": "DEF", "rating": 81, "team": "Barcelona" },
  { "id": 183, "name": "Alejandro Balde", "position": "DEF", "rating": 83, "team": "Barcelona" },
  { "id": 184, "name": "Marc Casadó", "position": "MID", "rating": 77, "team": "Barcelona" },
  { "id": 185, "name": "Pedri", "position": "MID", "rating": 87, "team": "Barcelona" },
  { "id": 186, "name": "Gavi", "position": "MID", "rating": 85, "team": "Barcelona" },
  { "id": 187, "name": "Lamine Yamal", "position": "FWD", "rating": 88, "team": "Barcelona" },
  { "id": 188, "name": "Marcus Rashford", "position": "FWD", "rating": 83, "team": "Barcelona" },
  { "id": 189, "name": "Robert Lewandowski", "position": "FWD", "rating": 86, "team": "Barcelona" },
  { "id": 190, "name": "Joan García", "position": "GK", "rating": 76, "team": "Barcelona" },
  { "id": 191, "name": "Wojciech Szczęsny", "position": "GK", "rating": 80, "team": "Barcelona" },
  { "id": 192, "name": "João Cancelo", "position": "DEF", "rating": 84, "team": "Barcelona" },
  { "id": 193, "name": "Andreas Christensen", "position": "DEF", "rating": 82, "team": "Barcelona" },
  { "id": 194, "name": "Eric García", "position": "DEF", "rating": 79, "team": "Barcelona" },
  { "id": 195, "name": "Gerard Martín", "position": "DEF", "rating": 72, "team": "Barcelona" },
  { "id": 196, "name": "Iñigo Martínez", "position": "DEF", "rating": 80, "team": "Barcelona" },
  { "id": 197, "name": "Frenkie de Jong", "position": "MID", "rating": 87, "team": "Barcelona" },
  { "id": 198, "name": "Dani Olmo", "position": "MID", "rating": 84, "team": "Barcelona" },
  { "id": 199, "name": "Fermín López", "position": "MID", "rating": 80, "team": "Barcelona" },
  { "id": 200, "name": "Marc Bernal", "position": "MID", "rating": 74, "team": "Barcelona" },
  { "id": 201, "name": "Raphinha", "position": "FWD", "rating": 84, "team": "Barcelona" },
  { "id": 202, "name": "Ferran Torres", "position": "FWD", "rating": 81, "team": "Barcelona" },
  { "id": 203, "name": "Roony Bardghji", "position": "FWD", "rating": 77, "team": "Barcelona" },
  { "id": 204, "name": "Pau Víctor", "position": "FWD", "rating": 72, "team": "Barcelona" },

  // --- ATLETICO MADRID ---
  { "id": 205, "name": "Jan Oblak", "position": "GK", "rating": 88, "team": "Atlético Madrid" },
  { "id": 206, "name": "Nahuel Molina", "position": "DEF", "rating": 81, "team": "Atlético Madrid" },
  { "id": 207, "name": "Robin Le Normand", "position": "DEF", "rating": 83, "team": "Atlético Madrid" },
  { "id": 208, "name": "José María Giménez", "position": "DEF", "rating": 84, "team": "Atlético Madrid" },
  { "id": 209, "name": "Dávid Hancko", "position": "DEF", "rating": 82, "team": "Atlético Madrid" },
  { "id": 210, "name": "Samuel Lino", "position": "DEF", "rating": 81, "team": "Atlético Madrid" },
  { "id": 211, "name": "Koke", "position": "MID", "rating": 82, "team": "Atlético Madrid" },
  { "id": 212, "name": "Pablo Barrios", "position": "MID", "rating": 79, "team": "Atlético Madrid" },
  { "id": 213, "name": "Nico González", "position": "MID", "rating": 79, "team": "Atlético Madrid" },
  { "id": 214, "name": "Antoine Griezmann", "position": "FWD", "rating": 88, "team": "Atlético Madrid" },
  { "id": 215, "name": "Julián Alvarez", "position": "FWD", "rating": 87, "team": "Atlético Madrid" },
  { "id": 216, "name": "Juan Musso", "position": "GK", "rating": 79, "team": "Atlético Madrid" },
  { "id": 217, "name": "Clément Lenglet", "position": "DEF", "rating": 78, "team": "Atlético Madrid" },
  { "id": 218, "name": "Matteo Ruggeri", "position": "DEF", "rating": 77, "team": "Atlético Madrid" },
  { "id": 219, "name": "Marc Pubill", "position": "DEF", "rating": 76, "team": "Atlético Madrid" },
  { "id": 220, "name": "Thomas Lemar", "position": "MID", "rating": 79, "team": "Atlético Madrid" },
  { "id": 221, "name": "Johnny Cardoso", "position": "MID", "rating": 77, "team": "Atlético Madrid" },
  { "id": 222, "name": "Marcos Llorente", "position": "MID", "rating": 83, "team": "Atlético Madrid" },
  { "id": 223, "name": "Alexander Sørloth", "position": "FWD", "rating": 81, "team": "Atlético Madrid" },
  { "id": 224, "name": "Giuliano Simeone", "position": "FWD", "rating": 74, "team": "Atlético Madrid" },
  { "id": 225, "name": "Conor Gallagher", "position": "MID", "rating": 82, "team": "Tottenham" }, // Satıldı

  // --- INTER ---
  { "id": 226, "name": "Yann Sommer", "position": "GK", "rating": 84, "team": "Inter" },
  { "id": 227, "name": "Benjamin Pavard", "position": "DEF", "rating": 83, "team": "Inter" },
  { "id": 228, "name": "Francesco Acerbi", "position": "DEF", "rating": 82, "team": "Inter" },
  { "id": 229, "name": "Alessandro Bastoni", "position": "DEF", "rating": 87, "team": "Inter" },
  { "id": 230, "name": "Denzel Dumfries", "position": "DEF", "rating": 82, "team": "Inter" },
  { "id": 231, "name": "Nicolò Barella", "position": "MID", "rating": 88, "team": "Inter" },
  { "id": 232, "name": "Hakan Çalhanoğlu", "position": "MID", "rating": 86, "team": "Inter" },
  { "id": 233, "name": "Piotr Zieliński", "position": "MID", "rating": 82, "team": "Inter" },
  { "id": 234, "name": "Federico Dimarco", "position": "DEF", "rating": 85, "team": "Inter" },
  { "id": 235, "name": "Marcus Thuram", "position": "FWD", "rating": 85, "team": "Inter" },
  { "id": 236, "name": "Lautaro Martínez", "position": "FWD", "rating": 89, "team": "Inter" },
  { "id": 237, "name": "Josep Martínez", "position": "GK", "rating": 76, "team": "Inter" },
  { "id": 238, "name": "Manuel Akanji", "position": "DEF", "rating": 84, "team": "Inter" },
  { "id": 239, "name": "Yann Bisseck", "position": "DEF", "rating": 78, "team": "Inter" },
  { "id": 240, "name": "Davide Frattesi", "position": "MID", "rating": 81, "team": "Inter" },
  { "id": 241, "name": "Henrikh Mkhitaryan", "position": "MID", "rating": 80, "team": "Inter" },
  { "id": 242, "name": "Mehdi Taremi", "position": "FWD", "rating": 80, "team": "Inter" },
  { "id": 243, "name": "Tajon Buchanan", "position": "DEF", "rating": 76, "team": "Inter" },

  // --- AC MILAN ---
  { "id": 244, "name": "Mike Maignan", "position": "GK", "rating": 88, "team": "AC Milan" },
  { "id": 245, "name": "Fikayo Tomori", "position": "DEF", "rating": 83, "team": "AC Milan" },
  { "id": 246, "name": "Matteo Gabbia", "position": "DEF", "rating": 78, "team": "AC Milan" },
  { "id": 247, "name": "Koni De Winter", "position": "DEF", "rating": 76, "team": "AC Milan" },
  { "id": 248, "name": "Alexis Saelemaekers", "position": "MID", "rating": 78, "team": "AC Milan" },
  { "id": 249, "name": "Youssouf Fofana", "position": "MID", "rating": 81, "team": "AC Milan" },
  { "id": 250, "name": "Luka Modrić", "position": "MID", "rating": 83, "team": "AC Milan" },
  { "id": 251, "name": "Adrien Rabiot", "position": "MID", "rating": 82, "team": "AC Milan" },
  { "id": 252, "name": "Pervis Estupiñán", "position": "DEF", "rating": 81, "team": "AC Milan" },
  { "id": 253, "name": "Christopher Nkunku", "position": "FWD", "rating": 84, "team": "AC Milan" },
  { "id": 254, "name": "Rafael Leão", "position": "FWD", "rating": 87, "team": "AC Milan" },
  { "id": 255, "name": "Filippo Terracciano", "position": "GK", "rating": 72, "team": "AC Milan" },
  { "id": 256, "name": "Strahinja Pavlović", "position": "DEF", "rating": 78, "team": "AC Milan" },
  { "id": 257, "name": "Ruben Loftus-Cheek", "position": "MID", "rating": 79, "team": "AC Milan" },
  { "id": 258, "name": "Christian Pulisic", "position": "FWD", "rating": 83, "team": "AC Milan" },
  { "id": 259, "name": "Niclas Füllkrug", "position": "FWD", "rating": 81, "team": "AC Milan" },
  { "id": 260, "name": "Yunus Musah", "position": "MID", "rating": 77, "team": "AC Milan" },

  // --- JUVENTUS ---
  { "id": 261, "name": "Michele Di Gregorio", "position": "GK", "rating": 81, "team": "Juventus" },
  { "id": 262, "name": "Pierre Kalulu", "position": "DEF", "rating": 79, "team": "Juventus" },
  { "id": 263, "name": "Gleison Bremer", "position": "DEF", "rating": 86, "team": "Juventus" },
  { "id": 264, "name": "Federico Gatti", "position": "DEF", "rating": 79, "team": "Juventus" },
  { "id": 265, "name": "Andrea Cambiaso", "position": "DEF", "rating": 80, "team": "Juventus" },
  { "id": 266, "name": "Manuel Locatelli", "position": "MID", "rating": 82, "team": "Juventus" },
  { "id": 267, "name": "Khéphren Thuram", "position": "MID", "rating": 81, "team": "Juventus" },
  { "id": 268, "name": "Francisco Conceição", "position": "FWD", "rating": 78, "team": "Juventus" },
  { "id": 269, "name": "Teun Koopmeiners", "position": "MID", "rating": 84, "team": "Juventus" },
  { "id": 270, "name": "Kenan Yildiz", "position": "FWD", "rating": 80, "team": "Juventus" },
  { "id": 271, "name": "Dušan Vlahović", "position": "FWD", "rating": 85, "team": "Juventus" },
  { "id": 272, "name": "Mattia Perin", "position": "GK", "rating": 79, "team": "Juventus" },
  { "id": 273, "name": "Danilo", "position": "DEF", "rating": 80, "team": "Juventus" },
  { "id": 274, "name": "Juan Cabal", "position": "DEF", "rating": 75, "team": "Juventus" },
  { "id": 275, "name": "Weston McKennie", "position": "MID", "rating": 78, "team": "Juventus" },
  { "id": 276, "name": "Douglas Luiz", "position": "MID", "rating": 82, "team": "Juventus" },
  { "id": 277, "name": "Timothy Weah", "position": "FWD", "rating": 76, "team": "Juventus" },

  // --- BAYERN MUNICH ---
  { "id": 278, "name": "Manuel Neuer", "position": "GK", "rating": 85, "team": "Bayern Münih" },
  { "id": 279, "name": "Joshua Kimmich", "position": "MID", "rating": 88, "team": "Bayern Münih" },
  { "id": 280, "name": "Dayot Upamecano", "position": "DEF", "rating": 84, "team": "Bayern Münih" },
  { "id": 281, "name": "Jonathan Tah", "position": "DEF", "rating": 84, "team": "Bayern Münih" },
  { "id": 282, "name": "Alphonso Davies", "position": "DEF", "rating": 85, "team": "Bayern Münih" },
  { "id": 283, "name": "João Palhinha", "position": "MID", "rating": 85, "team": "Bayern Münih" },
  { "id": 284, "name": "Aleksandar Pavlović", "position": "MID", "rating": 79, "team": "Bayern Münih" },
  { "id": 285, "name": "Michael Olise", "position": "FWD", "rating": 83, "team": "Bayern Münih" },
  { "id": 286, "name": "Jamal Musiala", "position": "MID", "rating": 89, "team": "Bayern Münih" },
  { "id": 287, "name": "Luis Díaz", "position": "FWD", "rating": 85, "team": "Bayern Münih" },
  { "id": 288, "name": "Harry Kane", "position": "FWD", "rating": 91, "team": "Bayern Münih" },
  { "id": 289, "name": "Sven Ulreich", "position": "GK", "rating": 74, "team": "Bayern Münih" },
  { "id": 290, "name": "Kim Min-jae", "position": "DEF", "rating": 83, "team": "Bayern Münih" },
  { "id": 291, "name": "Hiroki Ito", "position": "DEF", "rating": 79, "team": "Bayern Münih" },
  { "id": 292, "name": "Konrad Laimer", "position": "MID", "rating": 81, "team": "Bayern Münih" },
  { "id": 293, "name": "Leon Goretzka", "position": "MID", "rating": 82, "team": "Bayern Münih" },
  { "id": 294, "name": "Serge Gnabry", "position": "FWD", "rating": 82, "team": "Bayern Münih" },
  { "id": 295, "name": "Mathys Tel", "position": "FWD", "rating": 78, "team": "Bayern Münih" },

  // --- LEVERKUSEN ---
  { "id": 296, "name": "Mark Flekken", "position": "GK", "rating": 80, "team": "Bayer Leverkusen" },
  { "id": 297, "name": "Edmond Tapsoba", "position": "DEF", "rating": 83, "team": "Bayer Leverkusen" },
  { "id": 298, "name": "Loïc Badé", "position": "DEF", "rating": 79, "team": "Bayer Leverkusen" },
  { "id": 299, "name": "Jarell Quansah", "position": "DEF", "rating": 77, "team": "Bayer Leverkusen" },
  { "id": 300, "name": "Arthur", "position": "DEF", "rating": 74, "team": "Bayer Leverkusen" },
  { "id": 301, "name": "Robert Andrich", "position": "MID", "rating": 81, "team": "Bayer Leverkusen" },
  { "id": 302, "name": "Aleix Garcia", "position": "MID", "rating": 80, "team": "Bayer Leverkusen" },
  { "id": 303, "name": "Alex Grimaldo", "position": "DEF", "rating": 86, "team": "Bayer Leverkusen" },
  { "id": 304, "name": "Jonas Hofmann", "position": "MID", "rating": 81, "team": "Bayer Leverkusen" },
  { "id": 305, "name": "Eliesse Ben Seghir", "position": "MID", "rating": 76, "team": "Bayer Leverkusen" },
  { "id": 306, "name": "Patrik Schick", "position": "FWD", "rating": 82, "team": "Bayer Leverkusen" },
  { "id": 307, "name": "Janis Blaswich", "position": "GK", "rating": 76, "team": "Bayer Leverkusen" },
  { "id": 308, "name": "Jeanuël Belocian", "position": "DEF", "rating": 73, "team": "Bayer Leverkusen" },
  { "id": 309, "name": "Exequiel Palacios", "position": "MID", "rating": 82, "team": "Bayer Leverkusen" },
  { "id": 310, "name": "Martin Terrier", "position": "FWD", "rating": 80, "team": "Bayer Leverkusen" },
  { "id": 311, "name": "Nathan Tella", "position": "FWD", "rating": 78, "team": "Bayer Leverkusen" },

  // --- LEIPZIG ---
  { "id": 312, "name": "Péter Gulácsi", "position": "GK", "rating": 81, "team": "RB Leipzig" },
  { "id": 313, "name": "Benjamin Henrichs", "position": "DEF", "rating": 80, "team": "RB Leipzig" },
  { "id": 314, "name": "Willi Orbán", "position": "DEF", "rating": 82, "team": "RB Leipzig" },
  { "id": 315, "name": "Castello Lukeba", "position": "DEF", "rating": 81, "team": "RB Leipzig" },
  { "id": 316, "name": "David Raum", "position": "DEF", "rating": 81, "team": "RB Leipzig" },
  { "id": 317, "name": "Nicolas Seiwald", "position": "MID", "rating": 78, "team": "RB Leipzig" },
  { "id": 318, "name": "Xaver Schlager", "position": "MID", "rating": 81, "team": "RB Leipzig" },
  { "id": 319, "name": "Christoph Baumgartner", "position": "MID", "rating": 80, "team": "RB Leipzig" },
  { "id": 320, "name": "Antonio Nusa", "position": "FWD", "rating": 77, "team": "RB Leipzig" },
  { "id": 321, "name": "Loïs Openda", "position": "FWD", "rating": 84, "team": "RB Leipzig" },
  { "id": 322, "name": "Johan Bakayoko", "position": "FWD", "rating": 80, "team": "RB Leipzig" },
  { "id": 323, "name": "Maarten Vandevoordt", "position": "GK", "rating": 76, "team": "RB Leipzig" },
  { "id": 324, "name": "Lukas Klostermann", "position": "DEF", "rating": 78, "team": "RB Leipzig" },
  { "id": 325, "name": "Eljif Elmas", "position": "MID", "rating": 79, "team": "RB Leipzig" },
  { "id": 326, "name": "Xavi Simons", "position": "MID", "rating": 85, "team": "RB Leipzig" }, // Kiralık notu düşülmüş ama takımda listelenmiş
  { "id": 327, "name": "Yussuf Poulsen", "position": "FWD", "rating": 76, "team": "RB Leipzig" },

  // --- PSG ---
  { "id": 328, "name": "Lucas Chevalier", "position": "GK", "rating": 80, "team": "PSG" },
  { "id": 329, "name": "Achraf Hakimi", "position": "DEF", "rating": 86, "team": "PSG" },
  { "id": 330, "name": "Marquinhos", "position": "DEF", "rating": 87, "team": "PSG" },
  { "id": 331, "name": "Willian Pacho", "position": "DEF", "rating": 80, "team": "PSG" },
  { "id": 332, "name": "Nuno Mendes", "position": "DEF", "rating": 84, "team": "PSG" },
  { "id": 333, "name": "João Neves", "position": "MID", "rating": 83, "team": "PSG" },
  { "id": 334, "name": "Vitinha", "position": "MID", "rating": 85, "team": "PSG" },
  { "id": 335, "name": "Warren Zaïre-Emery", "position": "MID", "rating": 82, "team": "PSG" },
  { "id": 336, "name": "Ousmane Dembélé", "position": "FWD", "rating": 85, "team": "PSG" },
  { "id": 337, "name": "Gonçalo Ramos", "position": "FWD", "rating": 81, "team": "PSG" },
  { "id": 338, "name": "Khvicha Kvaratskhelia", "position": "FWD", "rating": 87, "team": "PSG" },
  { "id": 339, "name": "Matvey Safonov", "position": "GK", "rating": 78, "team": "PSG" },
  { "id": 340, "name": "Lucas Beraldo", "position": "DEF", "rating": 78, "team": "PSG" },
  { "id": 341, "name": "Lucas Hernandez", "position": "DEF", "rating": 83, "team": "PSG" },
  { "id": 342, "name": "Fabián Ruiz", "position": "MID", "rating": 81, "team": "PSG" },
  { "id": 343, "name": "Bradley Barcola", "position": "FWD", "rating": 81, "team": "PSG" },
  { "id": 344, "name": "Désiré Doué", "position": "MID", "rating": 76, "team": "PSG" },
  { "id": 345, "name": "Randal Kolo Muani", "position": "FWD", "rating": 82, "team": "PSG" },

  // --- FENERBAHÇE ---
  { "id": 346, "name": "Ederson", "position": "GK", "rating": 88, "team": "Fenerbahçe" },
  { "id": 347, "name": "Bright Osayi-Samuel", "position": "DEF", "rating": 77, "team": "Fenerbahçe" },
  { "id": 348, "name": "Çağlar Söyüncü", "position": "DEF", "rating": 78, "team": "Fenerbahçe" },
  { "id": 349, "name": "Alexander Djiku", "position": "DEF", "rating": 78, "team": "Fenerbahçe" },
  { "id": 350, "name": "Jayden Oosterwolde", "position": "DEF", "rating": 76, "team": "Fenerbahçe" },
  { "id": 351, "name": "Fred", "position": "MID", "rating": 81, "team": "Fenerbahçe" },
  { "id": 352, "name": "Matteo Guendouzi", "position": "MID", "rating": 80, "team": "Fenerbahçe" },
  { "id": 353, "name": "İrfan Can Kahveci", "position": "MID", "rating": 79, "team": "Fenerbahçe" },
  { "id": 354, "name": "Sebastian Szymański", "position": "MID", "rating": 81, "team": "Fenerbahçe" },
  { "id": 355, "name": "Allan Saint-Maximin", "position": "FWD", "rating": 80, "team": "Fenerbahçe" },
  { "id": 356, "name": "Youssef En-Nesyri", "position": "FWD", "rating": 81, "team": "Fenerbahçe" },
  { "id": 357, "name": "Mert Günok", "position": "GK", "rating": 78, "team": "Fenerbahçe" },
  { "id": 358, "name": "Rodrigo Becão", "position": "DEF", "rating": 77, "team": "Fenerbahçe" },
  { "id": 359, "name": "Sofyan Amrabat", "position": "MID", "rating": 79, "team": "Fenerbahçe" },
  { "id": 360, "name": "İsmail Yüksek", "position": "MID", "rating": 77, "team": "Fenerbahçe" },
  { "id": 361, "name": "Cengiz Ünder", "position": "FWD", "rating": 77, "team": "Fenerbahçe" },
  { "id": 362, "name": "Edin Dzeko", "position": "FWD", "rating": 78, "team": "Fenerbahçe" },
  { "id": 363, "name": "Cenk Tosun", "position": "FWD", "rating": 73, "team": "Fenerbahçe" },
  { "id": 364, "name": "Dušan Tadić", "position": "FWD", "rating": 80, "team": "Fenerbahçe" },
  { "id": 365, "name": "Anthony Musaba", "position": "FWD", "rating": 74, "team": "Fenerbahçe" },

  // --- GALATASARAY ---
  { "id": 366, "name": "Fernando Muslera", "position": "GK", "rating": 79, "team": "Galatasaray" },
  { "id": 367, "name": "Wilfried Singo", "position": "DEF", "rating": 79, "team": "Galatasaray" },
  { "id": 368, "name": "Davinson Sánchez", "position": "DEF", "rating": 81, "team": "Galatasaray" },
  { "id": 369, "name": "Victor Nelsson", "position": "DEF", "rating": 79, "team": "Galatasaray" },
  { "id": 370, "name": "Ismail Jakobs", "position": "DEF", "rating": 75, "team": "Galatasaray" },
  { "id": 371, "name": "Lucas Torreira", "position": "MID", "rating": 82, "team": "Galatasaray" },
  { "id": 372, "name": "Gabriel Sara", "position": "MID", "rating": 79, "team": "Galatasaray" },
  { "id": 373, "name": "Leroy Sané", "position": "FWD", "rating": 83, "team": "Galatasaray" },
  { "id": 374, "name": "Dries Mertens", "position": "FWD", "rating": 78, "team": "Galatasaray" },
  { "id": 375, "name": "Barış Alper Yılmaz", "position": "FWD", "rating": 79, "team": "Galatasaray" },
  { "id": 376, "name": "Victor Osimhen", "position": "FWD", "rating": 88, "team": "Galatasaray" },
  { "id": 377, "name": "Uğurcan Çakır", "position": "GK", "rating": 80, "team": "Galatasaray" },
  { "id": 378, "name": "Günay Güvenç", "position": "GK", "rating": 72, "team": "Galatasaray" },
  { "id": 379, "name": "Kaan Ayhan", "position": "DEF", "rating": 76, "team": "Galatasaray" },
  { "id": 380, "name": "Elias Jelert", "position": "DEF", "rating": 74, "team": "Galatasaray" },
  { "id": 381, "name": "Kerem Demirbay", "position": "MID", "rating": 77, "team": "Galatasaray" },
  { "id": 382, "name": "Hakim Ziyech", "position": "FWD", "rating": 79, "team": "Galatasaray" },
  { "id": 383, "name": "Mauro Icardi", "position": "FWD", "rating": 83, "team": "Galatasaray" },
  { "id": 384, "name": "Michy Batshuayi", "position": "FWD", "rating": 78, "team": "Galatasaray" },

  // --- BEŞİKTAŞ ---
  { "id": 385, "name": "Ersin Destanoğlu", "position": "GK", "rating": 74, "team": "Beşiktaş" },
  { "id": 386, "name": "Jonas Svensson", "position": "DEF", "rating": 75, "team": "Beşiktaş" },
  { "id": 387, "name": "Gabriel Paulista", "position": "DEF", "rating": 78, "team": "Beşiktaş" },
  { "id": 388, "name": "Felix Uduokhai", "position": "DEF", "rating": 77, "team": "Beşiktaş" },
  { "id": 389, "name": "Arthur Masuaku", "position": "DEF", "rating": 76, "team": "Beşiktaş" },
  { "id": 390, "name": "Al-Musrati", "position": "MID", "rating": 79, "team": "Beşiktaş" },
  { "id": 391, "name": "Gedson Fernandes", "position": "MID", "rating": 81, "team": "Beşiktaş" },
  { "id": 392, "name": "Milot Rashica", "position": "FWD", "rating": 77, "team": "Beşiktaş" },
  { "id": 393, "name": "Rafa Silva", "position": "FWD", "rating": 82, "team": "Beşiktaş" },
  { "id": 394, "name": "Semih Kılıçsoy", "position": "FWD", "rating": 76, "team": "Beşiktaş" },
  { "id": 395, "name": "Tammy Abraham", "position": "FWD", "rating": 79, "team": "Beşiktaş" },
  { "id": 396, "name": "Emir Yaşar", "position": "GK", "rating": 65, "team": "Beşiktaş" },
  { "id": 397, "name": "Emirhan Topçu", "position": "DEF", "rating": 73, "team": "Beşiktaş" },
  { "id": 398, "name": "Wilfred Ndidi", "position": "MID", "rating": 78, "team": "Beşiktaş" },
  { "id": 399, "name": "Ernest Muçi", "position": "MID", "rating": 77, "team": "Beşiktaş" },
  { "id": 400, "name": "Ciro Immobile", "position": "FWD", "rating": 81, "team": "Beşiktaş" },
  { "id": 401, "name": "El Bilal Touré", "position": "FWD", "rating": 77, "team": "Beşiktaş" },
  { "id": 402, "name": "Mustafa Hekimoğlu", "position": "FWD", "rating": 68, "team": "Beşiktaş" },

  // --- TRABZONSPOR ---
  { "id": 403, "name": "André Onana", "position": "GK", "rating": 82, "team": "Trabzonspor" },
  { "id": 404, "name": "Pedro Malheiro", "position": "DEF", "rating": 74, "team": "Trabzonspor" },
  { "id": 405, "name": "Stefan Savić", "position": "DEF", "rating": 79, "team": "Trabzonspor" },
  { "id": 406, "name": "Arseniy Batagov", "position": "DEF", "rating": 72, "team": "Trabzonspor" },
  { "id": 407, "name": "Eren Elmalı", "position": "DEF", "rating": 74, "team": "Trabzonspor" },
  { "id": 408, "name": "Okay Yokuşlu", "position": "MID", "rating": 76, "team": "Trabzonspor" },
  { "id": 409, "name": "Batista Mendy", "position": "MID", "rating": 76, "team": "Trabzonspor" },
  { "id": 410, "name": "Edin Višća", "position": "FWD", "rating": 79, "team": "Trabzonspor" },
  { "id": 411, "name": "Muhammed Cham", "position": "MID", "rating": 75, "team": "Trabzonspor" },
  { "id": 412, "name": "Anthony Nwakaeme", "position": "FWD", "rating": 77, "team": "Trabzonspor" },
  { "id": 413, "name": "Paul Onuachu", "position": "FWD", "rating": 78, "team": "Trabzonspor" },
  { "id": 414, "name": "Onuralp Çevikkan", "position": "GK", "rating": 66, "team": "Trabzonspor" },
  { "id": 415, "name": "Stefano Denswil", "position": "DEF", "rating": 75, "team": "Trabzonspor" },
  { "id": 416, "name": "Ozan Tufan", "position": "MID", "rating": 75, "team": "Trabzonspor" },
  { "id": 417, "name": "Enis Bardhi", "position": "MID", "rating": 76, "team": "Trabzonspor" },
  { "id": 418, "name": "Denis Drăguș", "position": "FWD", "rating": 74, "team": "Trabzonspor" },
  { "id": 419, "name": "Chibuike Nwaiwu", "position": "DEF", "rating": 70, "team": "Trabzonspor" },

  // --- DİĞER / TRANSFERLER ---
  { "id": 420, "name": "Antony", "position": "FWD", "rating": 78, "team": "Real Betis" }
];

// 2. ADIM: Otomatik Türkçe Çevirici ve Veri Hazırlığı
// Bu kısım, listendeki GK, DEF gibi terimleri otomatik Türkçeye çevirir.
const positionMap = {
    "GK": "Kale",
    "DEF": "Defans",
    "MID": "Orta Saha",
    "FWD": "Forvet"
};

// Uygulamanın kullanacağı temiz veritabanı değişkeni: 'players'
const players = rawFootballData.map(player => {
    return {
        id: player.id,
        name: player.name,
        // Eğer veri İngilizce ise çevir, zaten Türkçe ise olduğu gibi bırak
        position: positionMap[player.position] || player.position, 
        rating: player.rating,
        team: player.team
    };
});

// Konsola bilgi verelim (F12 yapınca görünür)
console.log(`Veritabanı yüklendi. Toplam Oyuncu: ${players.length}`);
